#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: root1
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    #数据库索引，默认为0
    database: 0
    #redis服务器地址
    host: 127.0.0.1
    #redis服务器密码，默认为空
    password:
    #redis服务器端口号
    port: 6379
    pool:
      #连接池最大连接数，负数无限制
      max-active: 8
      #连接池最大阻塞等待时间，负值无限制
      max-wait: -1
      #连接池最大空闲连接数
      max-idle: 8
      #连接池最小空闲连接数
      min-idle: 0
    #连接超时时间
    timeout: 0



#mybatis 配置111
mybatis:
    mapper-locations: classpath:mapper/*.xml


